#!/usr/bin/env bash
#install nginx on the server

apt-get update
apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
ufw allow 'Nginx Full'
echo "Hello World!" > /etc/nginx/html/index.html
service nginx start
