#!/usr/bin/env bash
#install nginx on the server

apt-get update
apt-get -y install nginx
ufw allow 'Nginx Full'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
printf %s "server {
    listen  80;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://alx.com/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
