#!/usr/bin/env bash
#error 404 page not found

apt-get update
apt-get install -y nginx

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen  80;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html index.htm;

    location /redirect_me {
        return 301 http://alx.com/;
        }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}" > etc/nginx/sites-available/default

service nginx restart
