#!/usr/bin/env bash
# install and configure haproxy

sudo apt update
sudo apt install -y haproxy

server_config=\
"
frontend webserver
    bind *:80
    mode http
    default_backend webfarm

backend webfarm
    balance roundrobin
    server 119623-web-01 52.86.27.65:80 check
    server 119623-web-02 100.25.13.63:80 check
" echo $server_config | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
