#!/usr/bin/env bash
# install and configure haproxy

sudo apt update
sudo apt install -y haproxy

server_config=\
"
frontend webserver
    bind *:80
    mode http
    default_backend webfarm

backend webfarm
    mode http
    balance roundrobin
    server 119623-web-01 54.144.197.148:80 check
    server 119623-web-02 52.204.61.125:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo systemctl enable haproxy

sudo systemctl start haproxy
