#!/usr/bin/env bash
# install and configure haproxy

sudo apt update
sudo apt install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.old

echo"
frontend webserver
    bind *:80
    mode http
    default_backend webfarm

backend webfarm
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo systemctl enable haproxy

sudo systemctl start haproxy
