#!/usr/bin/env bash
#displays content of /etc/passwd
while IFS=: read -r username paswd uid gid udi hom com
do
	echo "The user $username is part of the the $gid gang,"\
		"lives in $hom and rides $com. $uid's place"\
		"isprotected by the passcode $paswd, more info"\
		"about the user here: $udi"
done < /etc/passwd
