#!/usr/bin/env bash
#display time for 12 hours and 59 minutes
i=0
HR=0
while [ $i -lt 61 ]
do
	((i++))
	if [ $HR -lt 12 ]
	then
		case $i in
			60)
				((HR++))
				echo "Hour: ${HR}"
				i=0;;
			*)
				echo $i;;
		esac
	fi
done
