#!/usr/bin/env bash
#use a while loop and case statement to display a list of numbers
i=0
while [ $i -lt 20 ]
do
	((i++))
	case $i in
		4) echo -e '4\nbad luck from China';;
		9) echo -e '9\nbad luck from Japan';;
		17) echo -e '17\nbad luck from Italy';;
		*) echo $i;;
	esac
done
